# Generated by Django 3.2.9 on 2021-11-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_articles_article_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
