# Generated by Django 3.2.9 on 2021-11-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
