# Generated by Django 3.2.9 on 2021-11-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_auto_20211127_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='text',
            field=models.CharField(max_length=200, verbose_name='Text'),
        ),
    ]
